import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/shared/styles/globals.css'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
})

export const metadata: Metadata = {
	title: 'Туду лист',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<link
				rel='apple-touch-icon-precomposed'
				sizes='114x114'
				type='image/svg+xml'
				href='https://static.wikia.nocookie.net/logopedia/images/d/dc/Microsoft_To-Do_2017_App_Button.svg/revision/latest/scale-to-width-down/250?cb=20170421203417'
			/>
			<link
				rel='icon'
				type='image/svg+xml'
				href='https://qualitaet-ist-mehrwert.de/wp-content/uploads/microsoft-to-do-365-logo.png'
			/>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<AppRouterCacheProvider>{children}</AppRouterCacheProvider>
			</body>
		</html>
	)
}
